"""
Manually curated inventory — proper tags, body shapes, occasions, colors.
Run once: python scripts/seed_inventory.py
"""
import sys, os, random
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.database import inventory_collection

INVENTORY = [
    # ── MALE TOPS ──────────────────────────────────────────────────────────
    {
        "id": "M_T_001",
        "name": "Arrow White Formal Shirt",
        "category": "top",
        "gender": "male",
        "occasion": ["formal", "professional", "casual"],
        "colors": ["white"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle", "pear", "apple"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "price": 1299,
        "brand": "Arrow",
        "brand_tier": "mid",
        "stock": 30,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838545/male_white_shirt_hddgki.png",
        "tags": ["male", "top", "formal", "professional", "casual", "shirt", "classic"],
    },
    {
        "id": "M_T_002",
        "name": "H&M White T-Shirt",
        "category": "top",
        "gender": "male",
        "occasion": ["casual", "daily"],
        "colors": ["white"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle", "pear", "apple"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "price": 599,
        "brand": "H&M",
        "brand_tier": "mid",
        "stock": 40,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838545/men_white_tshirt_c3dp7v.png",
        "tags": ["male", "top", "casual", "daily", "tshirt", "basic"],
    },
    {
        "id": "M_T_003",
        "name": "Zudio Black T-Shirt",
        "category": "top",
        "gender": "male",
        "occasion": ["casual", "daily"],
        "colors": ["black"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle", "pear", "apple"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "price": 499,
        "brand": "Zudio",
        "brand_tier": "budget",
        "stock": 40,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838523/male_black_tshirt_k8oo13.png",
        "tags": ["male", "top", "casual", "daily", "tshirt", "basic"],
    },
    {
        "id": "M_T_004",
        "name": "Zara Red T-Shirt",
        "category": "top",
        "gender": "male",
        "occasion": ["casual", "daily"],
        "colors": ["red"],
        "color_family": "warm",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle"],
        "suitable_skin_tones": ["medium", "olive", "tan", "dark", "deep"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "price": 799,
        "brand": "Zara",
        "brand_tier": "mid",
        "stock": 25,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838536/male_red_tshirt_gymdkh.png",
        "tags": ["male", "top", "casual", "daily", "tshirt", "bold"],
    },
    {
        "id": "M_T_005",
        "name": "Van Heusen Dark Blue Shirt",
        "category": "top",
        "gender": "male",
        "occasion": ["formal", "professional", "casual"],
        "colors": ["navy"],
        "color_family": "cool",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle", "pear"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "price": 1499,
        "brand": "Van Heusen",
        "brand_tier": "mid",
        "stock": 20,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838520/male_darkblue_shirt_b3kxhc.png",
        "tags": ["male", "top", "formal", "professional", "shirt", "navy"],
    },
    {
        "id": "M_T_006",
        "name": "Arrow Dark Green Shirt",
        "category": "top",
        "gender": "male",
        "occasion": ["casual", "professional"],
        "colors": ["green"],
        "color_family": "cool",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear"],
        "suitable_skin_tones": ["medium", "olive", "tan", "dark", "deep"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "price": 1199,
        "brand": "Arrow",
        "brand_tier": "mid",
        "stock": 20,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838540/male_darkgreen_shirt_obsmzp.png",
        "tags": ["male", "top", "casual", "professional", "shirt"],
    },
    {
        "id": "M_T_007",
        "name": "H&M Gray Shirt",
        "category": "top",
        "gender": "male",
        "occasion": ["casual", "professional"],
        "colors": ["grey"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle", "pear", "apple"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "price": 999,
        "brand": "H&M",
        "brand_tier": "mid",
        "stock": 25,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838531/male_gray_shirt_gfxe36.png",
        "tags": ["male", "top", "casual", "professional", "shirt", "neutral"],
    },
    {
        "id": "M_T_008",
        "name": "Levi's Beige Shirt",
        "category": "top",
        "gender": "male",
        "occasion": ["casual", "daily"],
        "colors": ["beige"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "apple"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "price": 1099,
        "brand": "Levi's",
        "brand_tier": "mid",
        "stock": 20,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838542/male_skin_shirt_lhbpyh.png",
        "tags": ["male", "top", "casual", "daily", "shirt", "earth-tone"],
    },
    {
        "id": "M_T_009",
        "name": "Zara Black Formal Shirt",
        "category": "top",
        "gender": "male",
        "occasion": ["formal", "professional", "casual"],
        "colors": ["black"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle", "pear", "apple"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "price": 1599,
        "brand": "Zara",
        "brand_tier": "mid",
        "stock": 20,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838495/male_black_shirt_iuxxaq.png",
        "tags": ["male", "top", "formal", "professional", "shirt", "classic"],
    },
    {
        "id": "M_T_010",
        "name": "H&M Striped Shirt",
        "category": "top",
        "gender": "male",
        "occasion": ["casual", "daily"],
        "colors": ["white"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "price": 899,
        "brand": "H&M",
        "brand_tier": "mid",
        "stock": 20,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838532/male_line_shirt_t6i5k4.png",
        "tags": ["male", "top", "casual", "daily", "shirt", "striped"],
    },
    {
        "id": "M_T_011",
        "name": "H&M Gray Sweatshirt",
        "category": "top",
        "gender": "male",
        "occasion": ["casual", "daily"],
        "colors": ["grey"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "apple"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "price": 1299,
        "brand": "H&M",
        "brand_tier": "mid",
        "stock": 20,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1774678673/gray_sweat_shirt_sheujc.png",
        "tags": ["male", "top", "casual", "daily", "sweatshirt", "comfort"],
    },

    # ── MALE BOTTOMS ───────────────────────────────────────────────────────
    {
        "id": "M_B_001",
        "name": "Levi's Black Slim Jeans",
        "category": "bottom",
        "gender": "male",
        "occasion": ["casual", "daily", "professional"],
        "colors": ["black"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle", "pear"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["28", "30", "32", "34", "36"],
        "price": 2499,
        "brand": "Levi's",
        "brand_tier": "mid",
        "stock": 30,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838536/male_black_jean_vgqzfy.png",
        "tags": ["male", "bottom", "casual", "daily", "jeans", "slim"],
    },
    {
        "id": "M_B_002",
        "name": "Levi's Blue Jeans",
        "category": "bottom",
        "gender": "male",
        "occasion": ["casual", "daily"],
        "colors": ["blue"],
        "color_family": "cool",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle", "pear"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["28", "30", "32", "34", "36"],
        "price": 2299,
        "brand": "Levi's",
        "brand_tier": "mid",
        "stock": 30,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838511/male_blue_jean_anirjt.png",
        "tags": ["male", "bottom", "casual", "daily", "jeans", "classic"],
    },
    {
        "id": "M_B_003",
        "name": "Zudio Dark Blue Jeans",
        "category": "bottom",
        "gender": "male",
        "occasion": ["casual", "daily", "professional"],
        "colors": ["navy"],
        "color_family": "cool",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle", "pear", "apple"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["28", "30", "32", "34", "36"],
        "price": 1299,
        "brand": "Zudio",
        "brand_tier": "budget",
        "stock": 35,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838511/male_darkblue_jean_lm1tzj.png",
        "tags": ["male", "bottom", "casual", "daily", "jeans", "dark"],
    },
    {
        "id": "M_B_004",
        "name": "H&M Baggy Jeans",
        "category": "bottom",
        "gender": "male",
        "occasion": ["casual", "daily"],
        "colors": ["blue"],
        "color_family": "cool",
        "suitable_body_shapes": ["rectangle", "inverted_triangle", "pear"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["28", "30", "32", "34", "36"],
        "price": 1799,
        "brand": "H&M",
        "brand_tier": "mid",
        "stock": 20,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838496/male_baggy_jean_lqr3j9.png",
        "tags": ["male", "bottom", "casual", "daily", "jeans", "baggy", "streetwear"],
    },
    {
        "id": "M_B_005",
        "name": "Levi's Skinny Black Jeans",
        "category": "bottom",
        "gender": "male",
        "occasion": ["casual", "daily"],
        "colors": ["black"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["28", "30", "32", "34"],
        "price": 2199,
        "brand": "Levi's",
        "brand_tier": "mid",
        "stock": 20,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838539/male_skiinyblack_jean_bs8idt.png",
        "tags": ["male", "bottom", "casual", "daily", "jeans", "skinny"],
    },
    {
        "id": "M_B_006",
        "name": "Arrow Formal Trousers",
        "category": "bottom",
        "gender": "male",
        "occasion": ["formal", "professional"],
        "colors": ["black"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle", "pear", "apple"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["28", "30", "32", "34", "36"],
        "price": 1999,
        "brand": "Arrow",
        "brand_tier": "mid",
        "stock": 25,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838534/male_formal_trouser_jpxj1w.png",
        "tags": ["male", "bottom", "formal", "professional", "trousers", "classic"],
    },

    # ── MALE OUTERS ────────────────────────────────────────────────────────
    {
        "id": "M_O_001",
        "name": "H&M White Hoodie",
        "category": "outer",
        "gender": "male",
        "occasion": ["casual", "daily"],
        "colors": ["white"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "apple"],
        "suitable_skin_tones": ["medium", "olive", "tan", "dark", "deep"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "price": 1999,
        "brand": "H&M",
        "brand_tier": "mid",
        "stock": 20,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838540/male_white_hoodie_vnsxtg.png",
        "tags": ["male", "outer", "casual", "daily", "hoodie"],
    },
    {
        "id": "M_O_002",
        "name": "Zara Brown Jacket",
        "category": "outer",
        "gender": "male",
        "occasion": ["casual", "daily"],
        "colors": ["brown"],
        "color_family": "warm",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle"],
        "suitable_skin_tones": ["medium", "olive", "tan", "dark", "deep"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "price": 3499,
        "brand": "Zara",
        "brand_tier": "mid",
        "stock": 15,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838520/male_brown_jacket_yxw6g8.png",
        "tags": ["male", "outer", "casual", "jacket", "earth-tone"],
    },
    {
        "id": "M_O_003",
        "name": "Zara Leather Jacket",
        "category": "outer",
        "gender": "male",
        "occasion": ["casual", "daily"],
        "colors": ["black"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "price": 4999,
        "brand": "Zara",
        "brand_tier": "mid",
        "stock": 10,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838535/male_leather_jacket_kusjka.png",
        "tags": ["male", "outer", "casual", "jacket", "leather", "edgy"],
    },
    {
        "id": "M_O_004",
        "name": "H&M Orange Jacket",
        "category": "outer",
        "gender": "male",
        "occasion": ["casual", "daily"],
        "colors": ["orange"],
        "color_family": "warm",
        "suitable_body_shapes": ["rectangle", "inverted_triangle"],
        "suitable_skin_tones": ["medium", "olive", "tan", "dark", "deep"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "price": 2999,
        "brand": "H&M",
        "brand_tier": "mid",
        "stock": 12,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838547/male_orange_jacket_hsvgpv.png",
        "tags": ["male", "outer", "casual", "jacket", "bold"],
    },

    # ── FEMALE TOPS ────────────────────────────────────────────────────────
    {
        "id": "F_T_001",
        "name": "Zara Pink Blouse",
        "category": "top",
        "gender": "female",
        "occasion": ["casual", "professional", "daily"],
        "colors": ["pink"],
        "color_family": "bright",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "apple"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 1299,
        "brand": "Zara",
        "brand_tier": "mid",
        "stock": 25,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838488/female_pink_blouse_olapby.png",
        "tags": ["female", "top", "casual", "professional", "blouse", "feminine"],
    },
    {
        "id": "F_T_002",
        "name": "H&M Black Hoodie",
        "category": "top",
        "gender": "female",
        "occasion": ["casual", "daily"],
        "colors": ["black"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "apple", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 1599,
        "brand": "H&M",
        "brand_tier": "mid",
        "stock": 25,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838483/female_black_hoodie_xgsuug.png",
        "tags": ["female", "top", "casual", "daily", "hoodie", "comfort"],
    },
    {
        "id": "F_T_003",
        "name": "FabIndia Kurti",
        "category": "top",
        "gender": "female",
        "occasion": ["casual", "professional", "daily"],
        "colors": ["multicolor"],
        "color_family": "bright",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "apple", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 999,
        "brand": "FabIndia",
        "brand_tier": "mid",
        "stock": 30,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1774678702/female_kurti_plixpa.png",
        "tags": ["female", "top", "casual", "professional", "ethnic", "kurti"],
    },
    {
        "id": "F_T_004",
        "name": "Zara Casual Top",
        "category": "top",
        "gender": "female",
        "occasion": ["casual", "daily"],
        "colors": ["multicolor"],
        "color_family": "bright",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 1199,
        "brand": "Zara",
        "brand_tier": "mid",
        "stock": 20,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1774678649/female_casual1_ee3rdp.png",
        "tags": ["female", "top", "casual", "daily"],
    },

    # ── FEMALE BOTTOMS ─────────────────────────────────────────────────────
    {
        "id": "F_B_001",
        "name": "Levi's Blue Denim Jeans",
        "category": "bottom",
        "gender": "female",
        "occasion": ["casual", "daily"],
        "colors": ["blue"],
        "color_family": "cool",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 2299,
        "brand": "Levi's",
        "brand_tier": "mid",
        "stock": 25,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838531/female_blue_denim_jean_vtucur.png",
        "tags": ["female", "bottom", "casual", "daily", "jeans", "denim"],
    },
    {
        "id": "F_B_002",
        "name": "H&M Blue Jeans",
        "category": "bottom",
        "gender": "female",
        "occasion": ["casual", "daily"],
        "colors": ["blue"],
        "color_family": "cool",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 1999,
        "brand": "H&M",
        "brand_tier": "mid",
        "stock": 25,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838489/female_blue_jean_j61stp.png",
        "tags": ["female", "bottom", "casual", "daily", "jeans"],
    },
    {
        "id": "F_B_003",
        "name": "Zara Black Shorts",
        "category": "bottom",
        "gender": "female",
        "occasion": ["casual", "daily"],
        "colors": ["black"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 1299,
        "brand": "Zara",
        "brand_tier": "mid",
        "stock": 20,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838493/femle_black_short_jean_xgbmrr.png",
        "tags": ["female", "bottom", "casual", "daily", "shorts"],
    },
    {
        "id": "F_B_004",
        "name": "H&M Denim Shorts",
        "category": "bottom",
        "gender": "female",
        "occasion": ["casual", "daily"],
        "colors": ["blue"],
        "color_family": "cool",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 1199,
        "brand": "H&M",
        "brand_tier": "mid",
        "stock": 20,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838489/female_short_jean_tivcri.png",
        "tags": ["female", "bottom", "casual", "daily", "shorts", "denim"],
    },
    {
        "id": "F_B_005",
        "name": "Levi's Shredded Blue Jeans",
        "category": "bottom",
        "gender": "female",
        "occasion": ["casual", "daily"],
        "colors": ["blue"],
        "color_family": "cool",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 2499,
        "brand": "Levi's",
        "brand_tier": "mid",
        "stock": 15,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838484/blue_shreded_jean_og2swi.png",
        "tags": ["female", "bottom", "casual", "daily", "jeans", "distressed"],
    },

    # ── FEMALE OUTERS ──────────────────────────────────────────────────────
    {
        "id": "F_O_001",
        "name": "Zara Beige Trench Coat",
        "category": "outer",
        "gender": "female",
        "occasion": ["formal", "professional", "casual"],
        "colors": ["beige"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "apple"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 3999,
        "brand": "Zara",
        "brand_tier": "mid",
        "stock": 15,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838489/female_trench_coat_caxkae.png",
        "tags": ["female", "outer", "formal", "professional", "coat", "classic"],
    },
    {
        "id": "F_O_002",
        "name": "Mango Trench Coat",
        "category": "outer",
        "gender": "female",
        "occasion": ["formal", "professional", "casual"],
        "colors": ["beige"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "apple"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 4499,
        "brand": "Mango",
        "brand_tier": "mid",
        "stock": 12,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838489/female_trench2_coat_nvvwki.png",
        "tags": ["female", "outer", "formal", "professional", "coat", "elegant"],
    },
    {
        "id": "F_O_003",
        "name": "H&M Black Hoodie Jacket",
        "category": "outer",
        "gender": "female",
        "occasion": ["casual", "daily"],
        "colors": ["black"],
        "color_family": "neutral",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "apple", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 1999,
        "brand": "H&M",
        "brand_tier": "mid",
        "stock": 20,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838483/black_hoodie_ry9tsl.png",
        "tags": ["female", "outer", "casual", "daily", "hoodie"],
    },

    # ── FEMALE DRESSES (top+bottom combined — treat as "top" category) ─────
    {
        "id": "F_D_001",
        "name": "Biba Wedding Lehenga",
        "category": "top",
        "gender": "female",
        "occasion": ["wedding", "formal"],
        "colors": ["multicolor"],
        "color_family": "bright",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "apple", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 8999,
        "brand": "Biba",
        "brand_tier": "premium",
        "stock": 10,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838496/female_weddng_dress_uy2irg.png",
        "tags": ["female", "top", "wedding", "formal", "ethnic", "lehenga"],
    },
    {
        "id": "F_D_002",
        "name": "W Wedding Dress",
        "category": "top",
        "gender": "female",
        "occasion": ["wedding", "formal"],
        "colors": ["multicolor"],
        "color_family": "bright",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "apple", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 7999,
        "brand": "W",
        "brand_tier": "premium",
        "stock": 10,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838496/female_wedding2_dress_plrlii.png",
        "tags": ["female", "top", "wedding", "formal", "ethnic"],
    },
    {
        "id": "F_D_003",
        "name": "FabIndia Wedding Dress",
        "category": "top",
        "gender": "female",
        "occasion": ["wedding", "formal"],
        "colors": ["multicolor"],
        "color_family": "bright",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "apple", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 6999,
        "brand": "FabIndia",
        "brand_tier": "premium",
        "stock": 10,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1774678693/female_wedding3_dress_hulqxg.png",
        "tags": ["female", "top", "wedding", "formal", "ethnic"],
    },
    {
        "id": "F_D_004",
        "name": "Manyavar Wedding Gown",
        "category": "top",
        "gender": "female",
        "occasion": ["wedding", "formal"],
        "colors": ["multicolor"],
        "color_family": "bright",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "apple", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 9999,
        "brand": "Manyavar",
        "brand_tier": "premium",
        "stock": 8,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1774678713/female_wedding4_dress_rewrcd.png",
        "tags": ["female", "top", "wedding", "formal", "ethnic", "gown"],
    },
    {
        "id": "F_D_005",
        "name": "Forever 21 Party Dress",
        "category": "top",
        "gender": "female",
        "occasion": ["wedding", "formal"],
        "colors": ["multicolor"],
        "color_family": "bright",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 2999,
        "brand": "Forever 21",
        "brand_tier": "mid",
        "stock": 15,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838486/female_party_wear_ztbrjy.png",
        "tags": ["female", "top", "wedding", "formal", "party"],
    },
    {
        "id": "F_D_006",
        "name": "Zara Party Outfit",
        "category": "top",
        "gender": "female",
        "occasion": ["wedding", "formal"],
        "colors": ["multicolor"],
        "color_family": "bright",
        "suitable_body_shapes": ["rectangle", "hourglass", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 3499,
        "brand": "Zara",
        "brand_tier": "mid",
        "stock": 15,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838489/female_party2_wear_jntcrc.png",
        "tags": ["female", "top", "wedding", "formal", "party"],
    },
    {
        "id": "F_D_007",
        "name": "FabAlley Party Wear",
        "category": "top",
        "gender": "female",
        "occasion": ["wedding", "formal"],
        "colors": ["multicolor"],
        "color_family": "bright",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 2799,
        "brand": "FabAlley",
        "brand_tier": "mid",
        "stock": 15,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1774678692/female_party3_wear_xcxluv.png",
        "tags": ["female", "top", "wedding", "formal", "party"],
    },
    {
        "id": "F_D_008",
        "name": "H&M Casual Dress",
        "category": "top",
        "gender": "female",
        "occasion": ["casual", "daily"],
        "colors": ["multicolor"],
        "color_family": "bright",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "apple"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 1999,
        "brand": "H&M",
        "brand_tier": "mid",
        "stock": 20,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838483/female_casual_dress_bjhxcf.png",
        "tags": ["female", "top", "casual", "daily", "dress"],
    },

    # ── FEMALE WEDDING BOTTOMS (paired with dresses above) ─────────────────
    {
        "id": "F_WB_001",
        "name": "Biba Lehenga Skirt",
        "category": "bottom",
        "gender": "female",
        "occasion": ["wedding", "formal"],
        "colors": ["multicolor"],
        "color_family": "bright",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "apple", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 4999,
        "brand": "Biba",
        "brand_tier": "premium",
        "stock": 10,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838485/blue_jean_goxwhc.png",
        "tags": ["female", "bottom", "wedding", "formal", "ethnic", "skirt"],
    },
    {
        "id": "F_WB_002",
        "name": "W Ethnic Skirt",
        "category": "bottom",
        "gender": "female",
        "occasion": ["wedding", "formal"],
        "colors": ["multicolor"],
        "color_family": "bright",
        "suitable_body_shapes": ["rectangle", "hourglass", "pear", "apple", "inverted_triangle"],
        "suitable_skin_tones": ["fair", "light", "medium", "olive", "tan", "dark", "deep"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "price": 3999,
        "brand": "W",
        "brand_tier": "premium",
        "stock": 10,
        "image": "https://res.cloudinary.com/duaemmg4c/image/upload/v1773838485/blue_jean_goxwhc.png",
        "tags": ["female", "bottom", "wedding", "formal", "ethnic", "skirt"],
    },
]


def build():
    inventory_collection.delete_many({})
    print("🗑️  Cleared old inventory\n")

    inventory_collection.insert_many(INVENTORY)

    male   = [x for x in INVENTORY if x["gender"] == "male"]
    female = [x for x in INVENTORY if x["gender"] == "female"]
    tops   = [x for x in INVENTORY if x["category"] == "top"]
    bots   = [x for x in INVENTORY if x["category"] == "bottom"]
    outers = [x for x in INVENTORY if x["category"] == "outer"]

    occ: dict = {}
    for item in INVENTORY:
        for o in item["occasion"]:
            occ[o] = occ.get(o, 0) + 1

    print(f"✅ Inventory seeded!")
    print(f"   Total:   {len(INVENTORY)}")
    print(f"   Male:    {len(male)}")
    print(f"   Female:  {len(female)}")
    print(f"   Tops:    {len(tops)}")
    print(f"   Bottoms: {len(bots)}")
    print(f"   Outers:  {len(outers)}")
    print(f"\n📋 By Occasion:")
    for o, c in sorted(occ.items()):
        print(f"   {o:15s}: {c}")
    print(f"\n🚀 Ready! Run: python run.py")


if __name__ == "__main__":
    build()